# Welcome to Jekyll!
#

# Site settings
title: Solar System Exploration Group
description: |
  University of Toronto  
  Department of Earth Sciences
owner: Solar System Exploration Group # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: ssxglab@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://uoftssxg.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/SSXGatUofT
  github: https://github.com/uoftssxg
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/UTSSXG/
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
